// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package main.java.pl.edu.uj.tcs.memoizer;

public final class StoredUser {
  private StoredUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 2;
    /**
     * <code>optional string email = 2;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // required int64 version = 3;
    /**
     * <code>required int64 version = 3;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int64 version = 3;</code>
     */
    long getVersion();

    // repeated .file_manager.Plugin plugin = 4;
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    java.util.List<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin> 
        getPluginList();
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin getPlugin(int index);
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    int getPluginCount();
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    java.util.List<? extends main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder> 
        getPluginOrBuilderList();
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder getPluginOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code file_manager.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              email_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                plugin_ = new java.util.ArrayList<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin>();
                mutable_bitField0_ |= 0x00000008;
              }
              plugin_.add(input.readMessage(main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          plugin_ = java.util.Collections.unmodifiableList(plugin_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.class, main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_;
    /**
     * <code>required int64 version = 3;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 version = 3;</code>
     */
    public long getVersion() {
      return version_;
    }

    // repeated .file_manager.Plugin plugin = 4;
    public static final int PLUGIN_FIELD_NUMBER = 4;
    private java.util.List<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin> plugin_;
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    public java.util.List<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin> getPluginList() {
      return plugin_;
    }
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    public java.util.List<? extends main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder> 
        getPluginOrBuilderList() {
      return plugin_;
    }
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    public int getPluginCount() {
      return plugin_.size();
    }
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin getPlugin(int index) {
      return plugin_.get(index);
    }
    /**
     * <code>repeated .file_manager.Plugin plugin = 4;</code>
     */
    public main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder getPluginOrBuilder(
        int index) {
      return plugin_.get(index);
    }

    private void initFields() {
      name_ = "";
      email_ = "";
      version_ = 0L;
      plugin_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPluginCount(); i++) {
        if (!getPlugin(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmailBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, version_);
      }
      for (int i = 0; i < plugin_.size(); i++) {
        output.writeMessage(4, plugin_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmailBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, version_);
      }
      for (int i = 0; i < plugin_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, plugin_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(main.java.pl.edu.uj.tcs.memoizer.StoredUser.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code file_manager.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements main.java.pl.edu.uj.tcs.memoizer.StoredUser.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.class, main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.Builder.class);
      }

      // Construct using main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPluginFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (pluginBuilder_ == null) {
          plugin_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          pluginBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_User_descriptor;
      }

      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.User getDefaultInstanceForType() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.getDefaultInstance();
      }

      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.User build() {
        main.java.pl.edu.uj.tcs.memoizer.StoredUser.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.User buildPartial() {
        main.java.pl.edu.uj.tcs.memoizer.StoredUser.User result = new main.java.pl.edu.uj.tcs.memoizer.StoredUser.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (pluginBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            plugin_ = java.util.Collections.unmodifiableList(plugin_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.plugin_ = plugin_;
        } else {
          result.plugin_ = pluginBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof main.java.pl.edu.uj.tcs.memoizer.StoredUser.User) {
          return mergeFrom((main.java.pl.edu.uj.tcs.memoizer.StoredUser.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(main.java.pl.edu.uj.tcs.memoizer.StoredUser.User other) {
        if (other == main.java.pl.edu.uj.tcs.memoizer.StoredUser.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (pluginBuilder_ == null) {
          if (!other.plugin_.isEmpty()) {
            if (plugin_.isEmpty()) {
              plugin_ = other.plugin_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePluginIsMutable();
              plugin_.addAll(other.plugin_);
            }
            onChanged();
          }
        } else {
          if (!other.plugin_.isEmpty()) {
            if (pluginBuilder_.isEmpty()) {
              pluginBuilder_.dispose();
              pluginBuilder_ = null;
              plugin_ = other.plugin_;
              bitField0_ = (bitField0_ & ~0x00000008);
              pluginBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPluginFieldBuilder() : null;
            } else {
              pluginBuilder_.addAllMessages(other.plugin_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        for (int i = 0; i < getPluginCount(); i++) {
          if (!getPlugin(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        main.java.pl.edu.uj.tcs.memoizer.StoredUser.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (main.java.pl.edu.uj.tcs.memoizer.StoredUser.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 2;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 2;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }

      // required int64 version = 3;
      private long version_ ;
      /**
       * <code>required int64 version = 3;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 version = 3;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>required int64 version = 3;</code>
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 version = 3;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }

      // repeated .file_manager.Plugin plugin = 4;
      private java.util.List<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin> plugin_ =
        java.util.Collections.emptyList();
      private void ensurePluginIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          plugin_ = new java.util.ArrayList<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin>(plugin_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder, main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder> pluginBuilder_;

      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public java.util.List<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin> getPluginList() {
        if (pluginBuilder_ == null) {
          return java.util.Collections.unmodifiableList(plugin_);
        } else {
          return pluginBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public int getPluginCount() {
        if (pluginBuilder_ == null) {
          return plugin_.size();
        } else {
          return pluginBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin getPlugin(int index) {
        if (pluginBuilder_ == null) {
          return plugin_.get(index);
        } else {
          return pluginBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder setPlugin(
          int index, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePluginIsMutable();
          plugin_.set(index, value);
          onChanged();
        } else {
          pluginBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder setPlugin(
          int index, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.set(index, builderForValue.build());
          onChanged();
        } else {
          pluginBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder addPlugin(main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePluginIsMutable();
          plugin_.add(value);
          onChanged();
        } else {
          pluginBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder addPlugin(
          int index, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePluginIsMutable();
          plugin_.add(index, value);
          onChanged();
        } else {
          pluginBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder addPlugin(
          main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.add(builderForValue.build());
          onChanged();
        } else {
          pluginBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder addPlugin(
          int index, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.add(index, builderForValue.build());
          onChanged();
        } else {
          pluginBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder addAllPlugin(
          java.lang.Iterable<? extends main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin> values) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          super.addAll(values, plugin_);
          onChanged();
        } else {
          pluginBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder clearPlugin() {
        if (pluginBuilder_ == null) {
          plugin_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          pluginBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public Builder removePlugin(int index) {
        if (pluginBuilder_ == null) {
          ensurePluginIsMutable();
          plugin_.remove(index);
          onChanged();
        } else {
          pluginBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder getPluginBuilder(
          int index) {
        return getPluginFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder getPluginOrBuilder(
          int index) {
        if (pluginBuilder_ == null) {
          return plugin_.get(index);  } else {
          return pluginBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public java.util.List<? extends main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder> 
           getPluginOrBuilderList() {
        if (pluginBuilder_ != null) {
          return pluginBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(plugin_);
        }
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder addPluginBuilder() {
        return getPluginFieldBuilder().addBuilder(
            main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.getDefaultInstance());
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder addPluginBuilder(
          int index) {
        return getPluginFieldBuilder().addBuilder(
            index, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.getDefaultInstance());
      }
      /**
       * <code>repeated .file_manager.Plugin plugin = 4;</code>
       */
      public java.util.List<main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder> 
           getPluginBuilderList() {
        return getPluginFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder, main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder> 
          getPluginFieldBuilder() {
        if (pluginBuilder_ == null) {
          pluginBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder, main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder>(
                  plugin_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          plugin_ = null;
        }
        return pluginBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:file_manager.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:file_manager.User)
  }

  public interface PluginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string state = 5;
    /**
     * <code>required string state = 5;</code>
     */
    boolean hasState();
    /**
     * <code>required string state = 5;</code>
     */
    java.lang.String getState();
    /**
     * <code>required string state = 5;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();
  }
  /**
   * Protobuf type {@code file_manager.Plugin}
   */
  public static final class Plugin extends
      com.google.protobuf.GeneratedMessage
      implements PluginOrBuilder {
    // Use Plugin.newBuilder() to construct.
    private Plugin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Plugin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Plugin defaultInstance;
    public static Plugin getDefaultInstance() {
      return defaultInstance;
    }

    public Plugin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Plugin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 42: {
              bitField0_ |= 0x00000001;
              state_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_Plugin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_Plugin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.class, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder.class);
    }

    public static com.google.protobuf.Parser<Plugin> PARSER =
        new com.google.protobuf.AbstractParser<Plugin>() {
      public Plugin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Plugin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Plugin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string state = 5;
    public static final int STATE_FIELD_NUMBER = 5;
    private java.lang.Object state_;
    /**
     * <code>required string state = 5;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string state = 5;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string state = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      state_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(5, getStateBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code file_manager.Plugin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements main.java.pl.edu.uj.tcs.memoizer.StoredUser.PluginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_Plugin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_Plugin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.class, main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.Builder.class);
      }

      // Construct using main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.internal_static_file_manager_Plugin_descriptor;
      }

      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin getDefaultInstanceForType() {
        return main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.getDefaultInstance();
      }

      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin build() {
        main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin buildPartial() {
        main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin result = new main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin) {
          return mergeFrom((main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin other) {
        if (other == main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin.getDefaultInstance()) return this;
        if (other.hasState()) {
          bitField0_ |= 0x00000001;
          state_ = other.state_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (main.java.pl.edu.uj.tcs.memoizer.StoredUser.Plugin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string state = 5;
      private java.lang.Object state_ = "";
      /**
       * <code>required string state = 5;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string state = 5;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string state = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string state = 5;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 5;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 5;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:file_manager.Plugin)
    }

    static {
      defaultInstance = new Plugin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:file_manager.Plugin)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_file_manager_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_file_manager_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_file_manager_Plugin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_file_manager_Plugin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\014file_manager\"Z\n\004User\022\014\n\004na" +
      "me\030\001 \002(\t\022\r\n\005email\030\002 \001(\t\022\017\n\007version\030\003 \002(\003" +
      "\022$\n\006plugin\030\004 \003(\0132\024.file_manager.Plugin\"\027" +
      "\n\006Plugin\022\r\n\005state\030\005 \002(\tB.\n main.java.pl." +
      "edu.uj.tcs.memoizerB\nStoredUser"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_file_manager_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_file_manager_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_file_manager_User_descriptor,
              new java.lang.String[] { "Name", "Email", "Version", "Plugin", });
          internal_static_file_manager_Plugin_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_file_manager_Plugin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_file_manager_Plugin_descriptor,
              new java.lang.String[] { "State", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
